Repository RecruitRadar/RecruitRadar, pull requests merged in 2023-08, with the labels that each got.

#2 feat: add PR template
  .github/pull_request_template.md
Labels: 🔎 코드리뷰: 급해요

#7 feat: add wanted job scraper
  wanted_crawler/requirements.txt
  wanted_crawler/wanted_api.py
Labels: 🔎 코드리뷰: 천천히

#6 fix: issue and pr template
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/pull_request_template.md
Labels: 🔎 코드리뷰: 천천히

#9 Feat/add hajun
  README.md
  airflow/dags/rallit_api_call.py
  airflow/dags/test/rallit.py
  airflow/plugins/long_http_operator.py
  scraper_server/main.py
  scraper_server/plugin/rallit_class.py
  scraper_server/requirements.txt
  scraper_server/requirments.txt
  scraper_server/server.py
  scraper_server/static/rallit.json
Labels: 🔎 코드리뷰: 천천히

#10 feat: add python notebook for eda
  .gitignore
  README.md
  eda/EDA.ipynb
  eda/requirements.txt
Labels: 🔎 코드리뷰: 천천히

#11 feat: add JobPlanet FastAPI & Airflow DAG
  .gitignore
  README.md
  airflow/dags/jobplanet_api_call.py
  airflow/dags/plugins/jobplanet_class.py
  airflow/dags/test/jobplanet.py
  scraper/jobplanet_scraper/.gitignore
  scraper/jobplanet_scraper/jobplanet_api.py
  scraper_server/main.py
  scraper_server/plugin/jobplanet_class.py
  scraper_server/static/rallit.json
Labels: 🔎 코드리뷰: 천천히

#13 🐛 fix: heewon fastapi jobplanet env conflict resolve
  scraper_server/main.py
Labels: invalid, 🔎 코드리뷰: 천천히

#14 fix: scraper functions name
  scraper_server/main.py
Labels: 🔎 코드리뷰: 천천히

#18 Fix: Change "results" -> "result"
  README.md
  airflow/dags/test/jobplanet.py
  scraper/jobplanet_scraper/jobplanet_api.py
  scraper_server/plugin/jobplanet_class.py
Labels: 🔎 코드리뷰: 천천히

#31 ✨ feat: 1st preprocessing crawler add
  .github/workflows/scraper.yml
  airflow/dags/glue_crawler.py
Labels: 🔎 코드리뷰: 천천히

#32 feat: 1st preprocessing glue job script and notebook codes.
  glue/1st_preprocessing/de1_1_1st_preprocessing_script.py
  glue/1st_preprocessing/de1_1_1st_reprocessing_notebook.ipynb
Labels: 🔎 코드리뷰: 천천히

#36 Feat: 1차, 2차 전처리 스크립트, 노트북 수정 및 Airflow dag 수정
  airflow/dags/glue_crawler.py
  airflow/dags/glue_etl_job.py
  airflow/dags/glue_nlp_crawler.py
  glue/1st_preprocessing/de1_1_1st_preprocessing_notebook.ipynb
  glue/1st_preprocessing/de1_1_1st_preprocessing_script.py
  glue/1st_preprocessing/de1_1_1st_reprocessing_notebook.ipynb
  glue/2nd_preprocessing/de1_1_2nd_preprocessing_notebook.ipynb
  glue/2nd_preprocessing/de1_1_2nd_preprocessing_script.py
Labels: 🔎 코드리뷰: 천천히
